apiVersion: windtunnel.plantd.org/v1alpha1
kind: Experiment
metadata:
  name: experiment-test-pipeline
  namespace: test-pipeline
spec:
  pipelineRef:
    name: pipeline-test-pipeline
    namespace: test-pipeline
  endpointSpecs:
    - endpointName: upload
      dataSpec:
        dataSetRef:
          name: dataset-test-pipeline
          namespace: test-pipeline
      loadPatternRef:
        name: loadpattern-test-pipeline
        namespace: test-pipeline