apiVersion: windtunnel.plantd.org/v1alpha1
kind: Experiment
metadata:
  name: sample-experiment
  namespace: test-pipeline
spec:
  pipelineRef:
    name: sample-pipeline
  endpointSpecs:
    - endpointName: upload
      dataSpec:
        dataSetRef:
          name: sample-dataset
      loadPatternRef:
        name: sample-loadpattern
        namespace: test-pipeline
  useEndDetection: true
