apiVersion: windtunnel.plantd.org/v1alpha1
kind: LoadPattern
metadata:
  name: sample-loadpattern
  namespace: test-pipeline
spec:
  stages:
    - target: 10
      duration: 1m
    - target: 50
      duration: 1m
    - target: 40
      duration: 1m
  preAllocatedVUs: 30
  startRate: 30
  maxVUs: 100
  timeUnit: 1s
