apiVersion: windtunnel.plantd.org/v1alpha1
kind: Pipeline
metadata:
  name: sample-pipeline
  namespace: test-pipeline
spec:
  inCluster: true
  pipelineEndpoints:
    - name: upload
      http:
        url: http://phase1-service.test-pipeline.svc:3000/upload
        method: POST
  metricsEndpoint:
    serviceRef:
      name: opentelemetrycollector
    port: prometheus-port-1
  cloudProvider: aws
  tags: # Used for fetching the cost logs
    pipeline-infrastructure: testpipeline
  enableCostCalculation: true
