apiVersion: data.windtunnel/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema
    app.kubernetes.io/instance: schema
    app.kubernetes.io/part-of: plantd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd
  name:  product
  namespace: test-pipeline
spec:
  columns:
  - name: product_id
    type: uuid
  - name: product_name
    type: beername
  - name: quantity
    type: number
    params:
      min: 10
      max: 50
---
apiVersion: data.windtunnel/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema
    app.kubernetes.io/instance: schema
    app.kubernetes.io/part-of: plantd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd
  name:  supplier
  namespace: test-pipeline
spec:
  columns:
  - name: supplier_id
    type: uuid
  - name: supplier_name
    type: company
  - name: product_id
    type: uuid
    formula:
      name: Copy
      args: ["product.product_id"]
  - name: supplies_available
    type: number
    params:
      min: 100
      max: 500
---
apiVersion: data.windtunnel/v1alpha1
kind: Schema
metadata:
  labels:
    app.kubernetes.io/name: schema
    app.kubernetes.io/instance: schema
    app.kubernetes.io/part-of: plantd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: plantd
  name:  warehouse
  namespace: test-pipeline
spec:
  columns:
  - name: warehouse_id
    type: uuid
  - name: warehouse_name
    type: company
  - name: supplier_id
    type: uuid
    formula:
      name: Copy
      args: ["Supplier.supplier_id"]
  - name: product_id
    type: uuid
    formula:
      name: Copy
      args: ["Product.product_id"]
  - name: total_availability
    type: number
    params:
      min: 100
      max: 500