apiVersion: windtunnel.plantd.org/v1alpha1
kind: Simulation
metadata:
  name: sa-simulation
  namespace: test-pipeline
spec:
  digitalTwinRef:
    namespace: test-pipeline
    name: sa-dt
  trafficModelRef:
    namespace: test-pipeline
    name: sa-trafficmodel
  netCostRef:
    namespace: test-pipeline
    name: sa-netcost
  scenarioRef:
    namespace: test-pipeline
    name: sa-scenario
